name: Version and Publish NPM

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  version-and-publish:
    permissions:
      contents: write  # for changesets/action to push to the repo
      pull-requests: write  # for changesets/action to create PRs
    name: Version and Publish
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Clone repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: ./typescript

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./typescript

      - name: Version and/or Publish to NPM
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc
        with:
          commit: "chore: version typescript packages"
          title: "chore: version typescript packages"
          version: pnpm run changeset:version
          publish: pnpm run publish
          cwd: ./typescript
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
